In [1]:
import pandas as pd
table = pd.read_csv("cases.csv")

In [2]:
table

,CaseNumber,County,CountyName,Name,FillingDate,Status,ModifiedDate,ZipCodes
0,2021SC015147,40,Milwaukee,Rosso Rei LLC,2021-06-30,Open,7/1/2021 3:26:14 PM,53210
1,2021SC015145,40,Milwaukee,251 Bradley Place LLC,2021-06-30,Open,7/1/2021 3:22:54 PM,53208
2,2021SC015143,40,Milwaukee,Shirlean Clayton,2021-06-30,Open,7/1/2021 3:20:41 PM,53225
3,2021SC015142,40,Milwaukee,Milwaukee Moderne LLC,2021-06-30,Open,7/1/2021 3:19:44 PM,53203
4,2021SC015068,40,Milwaukee,David Butler,2021-06-30,Open,7/1/2021 2:08:30 PM,53212
...,...,...,...,...,...,...,...,...
1390,2021SC000070,21,Forest,Darrell Ward,2021-06-14,Open,6/22/2021 8:39:42 PM,54566
1391,2021SC000068,50,Price,David Ames,2021-06-04,Closed,7/6/2021 4:59:25 PM,54459
1392,2021SC000051,46,Pepin,John Robelia,2021-06-08,Closed,7/1/2021 4:13:39 PM,54721
1393,2021SC000038,26,Iron,Chadwin Bucknell,2021-06-23,Open,6/23/2021 6:30:14 PM,54525
1394,2021SC000016,19,Florence,RICHARD KOSKI,2021-06-04,Open,7/2/2021 4:49:28 PM,"54121,53150"

In [3]:
table = table[table['CountyName'] == 'Dane']

In [4]:
table

,CaseNumber,County,CountyName,Name,FillingDate,Status,ModifiedDate,ZipCodes
596,2021SC003171,13,Dane,Sabrinarae Oliva,2021-06-29,Open,6/30/2021 5:32:03 PM,53590
597,2021SC003163,13,Dane,TALON PLACE APARTMENTS LLC,2021-06-29,Open,6/30/2021 1:53:05 PM,53590
598,2021SC003161,13,Dane,Sunfield Townhomes LLC,2021-06-29,Open,6/29/2021 8:52:08 PM,53590
599,2021SC003158,13,Dane,McGlynn Properties LLC,2021-06-29,Open,7/6/2021 3:01:11 PM,NaN
600,2021SC003151,13,Dane,"East School Apartments, LLC",2021-06-28,Open,6/28/2021 4:38:15 PM,53589
...,...,...,...,...,...,...,...,...
701,2021SC002726,13,Dane,"Rolling Meadows Shopping Center, LLC",2021-06-02,Open,6/17/2021 4:03:20 PM,53711
703,2021SC002720,13,Dane,Kathleen Polasky,2021-06-02,Open,6/28/2021 4:20:39 PM,53714
704,2021SC002713,13,Dane,Susan Porter,2021-06-01,Closed,7/2/2021 2:17:56 PM,53597
705,2021SC002712,13,Dane,Sandra Howland,2021-06-01,Closed,6/4/2021 6:23:44 PM,53703
706,2021SC002710,13,Dane,Michael Kreisler,2021-06-01,Closed,6/16/2021 1:55:09 PM,53590

In [5]:
table = table.fillna(0)

In [6]:
table

,CaseNumber,County,CountyName,Name,FillingDate,Status,ModifiedDate,ZipCodes
596,2021SC003171,13,Dane,Sabrinarae Oliva,2021-06-29,Open,6/30/2021 5:32:03 PM,53590
597,2021SC003163,13,Dane,TALON PLACE APARTMENTS LLC,2021-06-29,Open,6/30/2021 1:53:05 PM,53590
598,2021SC003161,13,Dane,Sunfield Townhomes LLC,2021-06-29,Open,6/29/2021 8:52:08 PM,53590
599,2021SC003158,13,Dane,McGlynn Properties LLC,2021-06-29,Open,7/6/2021 3:01:11 PM,0
600,2021SC003151,13,Dane,"East School Apartments, LLC",2021-06-28,Open,6/28/2021 4:38:15 PM,53589
...,...,...,...,...,...,...,...,...
701,2021SC002726,13,Dane,"Rolling Meadows Shopping Center, LLC",2021-06-02,Open,6/17/2021 4:03:20 PM,53711
703,2021SC002720,13,Dane,Kathleen Polasky,2021-06-02,Open,6/28/2021 4:20:39 PM,53714
704,2021SC002713,13,Dane,Susan Porter,2021-06-01,Closed,7/2/2021 2:17:56 PM,53597
705,2021SC002712,13,Dane,Sandra Howland,2021-06-01,Closed,6/4/2021 6:23:44 PM,53703
706,2021SC002710,13,Dane,Michael Kreisler,2021-06-01,Closed,6/16/2021 1:55:09 PM,53590

In [ ]:
import requests
from bs4 import BeautifulSoup
import time

x = requests.get('https://wcca.wicourts.gov/caseDetail.html?caseNo=2021SC003151&countyNo=13')
soup = BeautifulSoup(x.content, 'html.parser')

In [ ]:
soup

In [7]:
from selenium import webdriver

PATH = 'C:\Program Files (x86)\chromedriver.exe'
driver = webdriver.Chrome(PATH)
driver.get('https://wcca.wicourts.gov/caseDetail.html?caseNo=2021SC003161&countyNo=13')

C:\Users\Patron\AppData\Local\Temp/ipykernel_17388/2627927964.py:4: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(PATH)

In [8]:
new_url = "https://wcca.wicourts.gov/caseDetail.html?caseNo=2021SC003171&countyNo=13"
driver.execute_script("window.open('');")
driver.switch_to.window(driver.window_handles[1])
driver.get(new_url)

In [ ]:
driver.get('https://wcca.wicourts.gov/caseDetail.html?caseNo=2021SC003163&countyNo=13')

In [ ]:
type(driver.page_source)

In [ ]:
columns = driver.find_element_by_class_name('columns')

In [ ]:
columns.text

In [9]:
def scrape(columns):
    index = 0
    plaintiffList=[]
    while index < len(columns.text):
            index = columns.text.find('Plaintiff', index)
            if index == -1:
                break
            plaintiffList.append(index)
            index += 2
    index = 0
    defendantList = []
    while index < len(columns.text):
            index = columns.text.find('Defendant', index)
            if index == -1:
                break
            defendantList.append(index)
            index += 2

    plaintiffName = []
    defendantName = []
    if plaintiffList[0]<defendantList[0]:
        for i in range(len(plaintiffList)):
            if i == len(plaintiffList) - 1:
                plaintiffName.append(columns.text[plaintiffList[i]+9:defendantList[0]].strip())
                break
            plaintiffName.append(columns.text[plaintiffList[i]+9:plaintiffList[i+1]].strip())

        for i in range(len(defendantList)):
            if i == len(defendantList) - 1:
                defendantName.append(columns.text[defendantList[i]+9:].strip())
                break
            defendantName.append(columns.text[defendantList[i]+9:defendantList[i+1]].strip())
        return plaintiffName, defendantName
    else:
        for i in range(len(defendantList)):
            if i == len(defendantList) - 1:
                defendantName.append(columns.text[defendantList[i]+9:plaintiffList[0]].strip())
                break
            defendantName.append(columns.text[defendantList[i]+9:defendantList[i+1]].strip())

        for i in range(len(plaintiffList)):
            if i == len(plaintiffList) - 1:
                plaintiffName.append(columns.text[plaintiffList[i]+9:].strip())
                break
            plaintiffName.append(columns.text[plaintiffList[i]+9:plaintiffList[i+1]].strip())
        return plaintiffName, defendantName

In [ ]:
x, y = scrape(columns)

In [ ]:
x

In [ ]:
y

In [15]:
import time
casesList = []
plaintiffsList = []
defendantsList = []
errorCount = 0
errorList = []
count = 1
for i in table['CaseNumber']:
    print(count)
    count += 1
    try:
        driver.get('https://wcca.wicourts.gov/caseDetail.html?caseNo={}&countyNo=13'.format(i))
        time.sleep(5)
        with open('cases\{}.html'.format(i), 'w') as f:
            f.write(driver.page_source)
        columns = driver.find_element_by_class_name('columns')
        plaintiffs, defendants = scrape(columns)
        casesList.append(i)
        plaintiffsList.append('; '.join(plaintiffs))
        defendantsList.append('; '.join(defendants))
    except:
        errorCount += 1
        errorList.append(i)

data = {"Caes": pd.Series(casesList),
        "plaintiffs": pd.Series(plaintiffsList),
        "defendants": pd.Series(defendantsList)}

df = pd.concat(data, axis = 1)
df.to_csv('table.csv', index = False)
print('errorCount:', errorCount)
print('errorList:', errorList)

1

C:\Users\Patron\AppData\Local\Temp/ipykernel_17388/3599543045.py:16: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  columns = driver.find_element_by_class_name('columns')

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
errorCount: 2
errorList: ['2021SC002881', '2021SC002840']

In [16]:
driver.quit()